// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serie.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	serie.proto
	user.proto

It has these top-level messages:
	Serie
	User
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Serie_Quality int32

const (
	Serie_HDTV   Serie_Quality = 0
	Serie_HD720  Serie_Quality = 1
	Serie_HD1080 Serie_Quality = 2
)

var Serie_Quality_name = map[int32]string{
	0: "HDTV",
	1: "HD720",
	2: "HD1080",
}
var Serie_Quality_value = map[string]int32{
	"HDTV":   0,
	"HD720":  1,
	"HD1080": 2,
}

func (x Serie_Quality) String() string {
	return proto.EnumName(Serie_Quality_name, int32(x))
}
func (Serie_Quality) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Serie_Language int32

const (
	Serie_VO     Serie_Language = 0
	Serie_VF     Serie_Language = 1
	Serie_VOSTFR Serie_Language = 2
)

var Serie_Language_name = map[int32]string{
	0: "VO",
	1: "VF",
	2: "VOSTFR",
}
var Serie_Language_value = map[string]int32{
	"VO":     0,
	"VF":     1,
	"VOSTFR": 2,
}

func (x Serie_Language) String() string {
	return proto.EnumName(Serie_Language_name, int32(x))
}
func (Serie_Language) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

type Serie struct {
	ID          string         `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name        string         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Url         string         `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Quality     Serie_Quality  `protobuf:"varint,4,opt,name=quality,enum=protobuf.Serie_Quality" json:"quality,omitempty"`
	Lang        Serie_Language `protobuf:"varint,5,opt,name=lang,enum=protobuf.Serie_Language" json:"lang,omitempty"`
	Season      int32          `protobuf:"varint,6,opt,name=season" json:"season,omitempty"`
	LastEpisode int32          `protobuf:"varint,7,opt,name=lastEpisode" json:"lastEpisode,omitempty"`
}

func (m *Serie) Reset()                    { *m = Serie{} }
func (m *Serie) String() string            { return proto.CompactTextString(m) }
func (*Serie) ProtoMessage()               {}
func (*Serie) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Serie) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Serie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Serie) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Serie) GetQuality() Serie_Quality {
	if m != nil {
		return m.Quality
	}
	return Serie_HDTV
}

func (m *Serie) GetLang() Serie_Language {
	if m != nil {
		return m.Lang
	}
	return Serie_VO
}

func (m *Serie) GetSeason() int32 {
	if m != nil {
		return m.Season
	}
	return 0
}

func (m *Serie) GetLastEpisode() int32 {
	if m != nil {
		return m.LastEpisode
	}
	return 0
}

func init() {
	proto.RegisterType((*Serie)(nil), "protobuf.Serie")
	proto.RegisterEnum("protobuf.Serie_Quality", Serie_Quality_name, Serie_Quality_value)
	proto.RegisterEnum("protobuf.Serie_Language", Serie_Language_name, Serie_Language_value)
}

func init() { proto.RegisterFile("serie.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0x41, 0x4b, 0xc3, 0x40,
	0x14, 0x84, 0x9b, 0x6d, 0xb2, 0x4d, 0x5f, 0xa1, 0x2c, 0xef, 0xa0, 0x7b, 0x0c, 0x39, 0x48, 0x10,
	0x09, 0x69, 0x3d, 0xe8, 0x0f, 0x58, 0x4b, 0x0a, 0x42, 0x71, 0x5b, 0x72, 0xdf, 0xe2, 0x1a, 0x02,
	0x31, 0xa9, 0xd9, 0xe4, 0xe0, 0x7f, 0xf2, 0x47, 0x4a, 0x5f, 0x1b, 0x10, 0x4f, 0x6f, 0x76, 0xe6,
	0x63, 0x66, 0x61, 0xe1, 0x6c, 0x57, 0xd9, 0xf4, 0xd4, 0xb5, 0x7d, 0x8b, 0x21, 0x9d, 0xe3, 0xf0,
	0x11, 0xff, 0x30, 0x08, 0xf6, 0xe7, 0x04, 0x97, 0xc0, 0xb6, 0x4a, 0x7a, 0x91, 0x97, 0xcc, 0x35,
	0xdb, 0x2a, 0x44, 0xf0, 0x1b, 0xf3, 0x69, 0x25, 0x23, 0x87, 0x34, 0x0a, 0x98, 0x0e, 0x5d, 0x2d,
	0xa7, 0x64, 0x9d, 0x25, 0xae, 0x60, 0xf6, 0x35, 0x98, 0xba, 0xea, 0xbf, 0xa5, 0x1f, 0x79, 0xc9,
	0x72, 0x7d, 0x9b, 0x8e, 0xdd, 0x29, 0xf5, 0xa6, 0x6f, 0x97, 0x58, 0x8f, 0x1c, 0x3e, 0x80, 0x5f,
	0x9b, 0xa6, 0x94, 0x01, 0xf1, 0xf2, 0x3f, 0xff, 0x6a, 0x9a, 0x72, 0x30, 0xa5, 0xd5, 0x44, 0xe1,
	0x0d, 0x70, 0x67, 0x8d, 0x6b, 0x1b, 0xc9, 0x23, 0x2f, 0x09, 0xf4, 0xf5, 0x85, 0x11, 0x2c, 0x6a,
	0xe3, 0xfa, 0x97, 0x53, 0xe5, 0xda, 0x77, 0x2b, 0x67, 0x14, 0xfe, 0xb5, 0xe2, 0x7b, 0x98, 0x5d,
	0xb7, 0x31, 0x04, 0x3f, 0x57, 0x87, 0x42, 0x4c, 0x70, 0x0e, 0x41, 0xae, 0x9e, 0xd6, 0x99, 0xf0,
	0x10, 0x80, 0xe7, 0x6a, 0x95, 0x3d, 0x67, 0x82, 0xc5, 0x77, 0x10, 0x8e, 0xbb, 0xc8, 0x81, 0x15,
	0x3b, 0x31, 0xa1, 0xbb, 0xb9, 0x70, 0xc5, 0x6e, 0x7f, 0xd8, 0x68, 0xc1, 0x8e, 0x9c, 0x3e, 0xfb,
	0xf8, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x74, 0x4d, 0x4e, 0x4e, 0x01, 0x00, 0x00,
}
